# Pandas.melt
Return reshaped DataFrame organized by given index / column values.

Reshape data (produce a “pivot” table) based on column values. Uses unique values from specified index / columns to form axes of the resulting DataFrame. This function does not support data aggregation, multiple values will result in a MultiIndex in the columns. See the User Guide for more on reshaping.

## Syntax:

```python
pandas.pivot(data, *, columns, index=<no_default>, values=<no_default>)

```
### Parameters:
* data: DataFrame
    * Input pandas DataFrame object.
* columns: Hashable or a sequence of the previous
    * Column(s) to use as identifier variables.

* index: Hashable or a sequence of the previous, optional
    * Column to use to make new frame’s index. If not given, uses existing index.

* values: Hashable or a sequence of the previous, optional
    * Column(s) to use for populating new frame’s values. If not specified, all remaining columns will be used and the result will have hierarchically indexed columns.

### Returns:
* DataFrame
    * Returns reshaped DataFrame.
### Raises:
* ValueError:
    * When there are any index, columns combinations with multiple values. DataFrame.pivot_table when you need to aggregate.  
    
## References
* https://pandas.pydata.org/docs/reference/api/pandas.pivot.html#pandas.pivot

# Libraries

In [2]:
import pandas as pd

# Example 1

In [3]:
df = pd.DataFrame(
    {
        "foo": ["one", "one", "one", "two", "two", "two"],
        "bar": ["A", "B", "C", "A", "B", "C"],
        "baz": [1, 2, 3, 4, 5, 6],
        "zoo": ["x", "y", "z", "q", "w", "t"],
    }
)
df

   foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

In [4]:
df.pivot(index="foo", columns="bar", values="baz")

bar  A  B  C
foo
one  1  2  3
two  4  5  6

In [5]:
df.pivot(index="foo", columns="bar")["baz"]

bar  A  B  C
foo
one  1  2  3
two  4  5  6

In [6]:
df.pivot(index="foo", columns="bar", values=["baz", "zoo"])

    baz       zoo
bar   A  B  C   A  B  C
foo
one   1  2  3   x  y  z
two   4  5  6   q  w  t

# You could also assign a list of column names or a list of index names.

In [7]:
df = pd.DataFrame(
    {
        "lev1": [1, 1, 1, 2, 2, 2],
        "lev2": [1, 1, 2, 1, 1, 2],
        "lev3": [1, 2, 1, 2, 1, 2],
        "lev4": [1, 2, 3, 4, 5, 6],
        "values": [0, 1, 2, 3, 4, 5],
    }
)
df

   lev1  lev2  lev3  lev4  values
0     1     1     1     1       0
1     1     1     2     2       1
2     1     2     1     3       2
3     2     1     2     4       3
4     2     1     1     5       4
5     2     2     2     6       5

In [8]:
df.pivot(index="lev1", columns=["lev2", "lev3"], values="values")

lev2    1         2
lev3    1    2    1    2
lev1
1     0.0  1.0  2.0  NaN
2     4.0  3.0  NaN  5.0

In [9]:
df.pivot(index=["lev1", "lev2"], columns=["lev3"], values="values")

lev3         1    2
lev1 lev2
1    1     0.0  1.0
     2     2.0  NaN
2    1     4.0  3.0
     2     NaN  5.0

# A ValueError is raised if there are any duplicates.

In [10]:
df = pd.DataFrame(
    {
        "foo": ["one", "one", "two", "two"],
        "bar": ["A", "A", "B", "C"],
        "baz": [1, 2, 3, 4],
    }
)
df

   foo bar  baz
0  one   A    1
1  one   A    2
2  two   B    3
3  two   C    4

In [11]:
df.pivot(index="foo", columns="bar", values="baz")

ValueError: Index contains duplicate entries, cannot reshape